/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Clases.Cliente;
import static Interfaces.Bienvenidos.hospedados;
import javax.swing.JOptionPane;

/**
 *
 * @author Victoria Saldivia
 */
public class BuscarHosp extends javax.swing.JFrame {

    /**
     * Creates new form BuscarHosp
     */
    public BuscarHosp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ApellidoTexto = new javax.swing.JTextField();
        NombreTexto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayScreen = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 139));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BUSCAR HOSPEDADOS");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 390, -1));

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 51, 139));
        Back.setText("⇦");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 70));

        Buscar.setBackground(new java.awt.Color(0, 51, 139));
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 220, -1));

        jLabel1.setBackground(new java.awt.Color(0, 51, 139));
        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 139));
        jLabel1.setText("Apellido:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, -1));

        jLabel2.setBackground(new java.awt.Color(0, 51, 139));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 139));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HABITACIÓN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 190, -1));

        jLabel3.setBackground(new java.awt.Color(0, 51, 139));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 139));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, -1));

        jLabel5.setBackground(new java.awt.Color(0, 51, 139));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 139));
        jLabel5.setText("Datos del Cliente:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 240, -1));

        ApellidoTexto.setBackground(new java.awt.Color(255, 255, 255));
        ApellidoTexto.setForeground(new java.awt.Color(0, 0, 0));
        ApellidoTexto.setText("Introduzca el apellido...");
        ApellidoTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, java.awt.Color.white, java.awt.Color.blue));
        ApellidoTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ApellidoTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ApellidoTextoFocusLost(evt);
            }
        });
        ApellidoTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoTextoKeyTyped(evt);
            }
        });
        jPanel1.add(ApellidoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, -1));

        NombreTexto.setBackground(new java.awt.Color(255, 255, 255));
        NombreTexto.setForeground(new java.awt.Color(0, 0, 0));
        NombreTexto.setText("Introduzca el nombre...");
        NombreTexto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.blue, java.awt.Color.white, java.awt.Color.white, java.awt.Color.blue));
        NombreTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NombreTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NombreTextoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreTextoFocusLost(evt);
            }
        });
        NombreTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTextoActionPerformed(evt);
            }
        });
        NombreTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreTextoKeyTyped(evt);
            }
        });
        jPanel1.add(NombreTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 220, -1));

        DisplayScreen.setEditable(false);
        DisplayScreen.setBackground(new java.awt.Color(255, 255, 255));
        DisplayScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.white, java.awt.Color.blue));
        DisplayScreen.setForeground(new java.awt.Color(204, 204, 204));
        DisplayScreen.setFocusable(false);
        jScrollPane1.setViewportView(DisplayScreen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 190, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        
        String nombre = NombreTexto.getText();
        String apellido = ApellidoTexto.getText();
        
        Cliente cliente = new Cliente(nombre, apellido);
        
     
        if(hospedados.isInHashIndexN(cliente) != -1){
          JOptionPane.showMessageDialog(null,"El cliente" + cliente.getNombre() + " "+ cliente.getApellido() + " esta hospedado en la habitacion " + hospedados.isInHashIndexN(cliente));
        }else{
            JOptionPane.showMessageDialog(null,"El cliente no esta hospedado en el hotel");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Menu VentanaMenu = new Menu();
        
        this.setVisible(false);
        VentanaMenu.setLocationRelativeTo(null);
        VentanaMenu.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void NombreTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreTextoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar(); 
        boolean esLetra = Character.isLetter(key) || key == 'á' || key == 'é' || key == 'í' || key == 'ó' || key == 'ú' || key == 'ü' || key == 'ñ' || key == 'Á' || key == 'É' || key == 'Í' || key == 'Ó' || key == 'Ú' || key == 'Ü' || key == 'Ñ';
        if (!esLetra) { 
            evt.consume(); 
        }

    }//GEN-LAST:event_NombreTextoKeyTyped

    private void ApellidoTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoTextoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar(); 
        boolean esLetra = Character.isLetter(key) || key == 'á' || key == 'é' || key == 'í' || key == 'ó' || key == 'ú' || key == 'ü' || key == 'ñ' || key == 'Á' || key == 'É' || key == 'Í' || key == 'Ó' || key == 'Ú' || key == 'Ü' || key == 'Ñ';
        if (!esLetra) { 
            evt.consume(); 
        }

    }//GEN-LAST:event_ApellidoTextoKeyTyped

    private void NombreTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreTextoFocusGained
        // TODO add your handling code here:
        NombreTexto.setText("");
    }//GEN-LAST:event_NombreTextoFocusGained

    private void ApellidoTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoTextoFocusGained
        // TODO add your handling code here:
        ApellidoTexto.setText("");
    }//GEN-LAST:event_ApellidoTextoFocusGained

    private void NombreTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreTextoFocusLost
        // TODO add your handling code here:
        if(NombreTexto.getText().isBlank()){
            NombreTexto.setText("Introduzca el nombre...");
        }
    }//GEN-LAST:event_NombreTextoFocusLost

    private void NombreTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTextoActionPerformed

    private void ApellidoTextoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoTextoFocusLost
        // TODO add your handling code here:
        if(ApellidoTexto.getText().isBlank()){
            ApellidoTexto.setText("Introduzca el apellido...");
        }
    }//GEN-LAST:event_ApellidoTextoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarHosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarHosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarHosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarHosp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarHosp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoTexto;
    private javax.swing.JButton Back;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextPane DisplayScreen;
    private javax.swing.JTextField NombreTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
